// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CatalogRefresh = { 
/**
 * False when skipped (checked recently, or automatic checks are off).
 */
checked: boolean, updated: boolean, version: number, };
