// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningFormat } from "./ReasoningFormat";
import type { Sampling } from "./Sampling";
import type { ThinkingControl } from "./ThinkingControl";

export type ChatProfile = { 
/**
 * How the model marks its private reasoning in the output.
 */
reasoning: ReasoningFormat, 
/**
 * How thinking is switched on and off through the chat template.
 */
thinking: ThinkingControl, 
/**
 * Recommended sampling for normal replies.
 */
sampling: Sampling, 
/**
 * Recommended sampling when thinking is on, if different.
 */
thinking_sampling: Sampling | null, };
