// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CpuInfo = { name: string, cores: number, threads: number, arch: string, 
/**
 * Instruction set extensions relevant to inference speed (for the Advanced report).
 */
features: Array<string>, };
