// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DownloadError = { "kind": "cancelled" } | { "kind": "offline" } | { "kind": "network", message: string, } | { "kind": "not_enough_space", need_bytes: number, free_bytes: number, } | { "kind": "corrupt" } | { "kind": "http", status: number, } | { "kind": "io", message: string, };
