// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FitLabel } from "./FitLabel";
import type { Placement } from "./Placement";

export type Fit = { label: FitLabel, placement: Placement, 
/**
 * Context (tokens) the estimate was made for; used when loading.
 */
context: number, need_bytes: number, 
/**
 * How much more memory the device would need (TooBig only).
 */
short_by_bytes: number, 
/**
 * It fits the device, but not the memory free right now: other apps should be closed.
 */
close_other_apps: boolean, };
