// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GpuChoice = { "kind": "none" } | { "kind": "auto", device_index: number, } | { "kind": "all" } | { "kind": "layers", count: number, };
