// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LlmError = { "kind": "not_loaded" } | { "kind": "load_failed", message: string, } | { "kind": "context_full" } | { "kind": "runtime", message: string, };
