// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Memory model used to decide whether a model fits (see `fit`). For catalog models these numbers
 * are measured by `catalog-tool verify` from llama.cpp's own buffer allocations.
 */
export type MemoryProfile = { 
/**
 * Model weights as loaded (≈ file size).
 */
weights_bytes: number, 
/**
 * KV cache cost per context token for full-attention layers (f16 cache).
 */
kv_bytes_per_token: number, 
/**
 * KV cache per token for sliding-window layers; those only keep `swa_window` tokens.
 */
swa_kv_bytes_per_token: number, swa_window: number, 
/**
 * Context-independent state (recurrent layers etc.).
 */
fixed_bytes: number, 
/**
 * Compute scratch buffer per token of micro-batch (dominated by vocab size).
 */
compute_bytes_per_ubatch_token: number, 
/**
 * Longest context the model was trained for.
 */
max_context: number, };
