// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Memory the model may use on this device.
 */
export type MemoryPools = { 
/**
 * Usable dedicated graphics memory (discrete GPUs only), 0 if none or disabled.
 */
gpu_bytes: number, 
/**
 * GPU and CPU share system memory and the GPU does the work (Apple silicon, iPhone).
 */
unified_gpu: boolean, 
/**
 * System memory the model may use and still leave the device responsive.
 */
comfortable_bytes: number, 
/**
 * Absolute ceiling before the OS starts killing apps or swapping heavily.
 */
limit_bytes: number, 
/**
 * Free system memory right now.
 */
available_now_bytes: number, };
