// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelFile = { 
/**
 * Hugging Face repo, e.g. "unsloth/Qwen3.5-4B-GGUF".
 */
repo: string, 
/**
 * Pinned 40-char commit.
 */
revision: string, path: string, size: number, sha256: string, };
