// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Progress = { "stage": "checking_partial", done: number, total: number, } | { "stage": "downloading", done: number, total: number, 
/**
 * Measured over the last few seconds; None until there's enough data.
 */
bytes_per_second: number | null, } | { "stage": "retrying", attempt: number, max_attempts: number, wait_seconds: number, };
