// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Plain-language verdict for a measured speed, relative to reading speed.
 */
export type SpeedVerdict = "faster_than_reading" | "about_reading_speed" | "slower_than_reading" | "slow";
