// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BenchmarkResult } from "./BenchmarkResult";
import type { CatalogModel } from "./CatalogModel";
import type { ConversationSummary } from "./ConversationSummary";
import type { ImportedModel } from "./ImportedModel";
import type { LoadedModel } from "./LoadedModel";
import type { PartialDownload } from "./PartialDownload";
import type { Platform } from "./Platform";
import type { Settings } from "./Settings";

/**
 * Everything the UI needs to render its screens, in one call.
 */
export type AppState = { app_version: string, platform: Platform, settings: Settings, catalog_version: number, models: Array<CatalogModel>, imported: Array<ImportedModel>, installed: Array<string>, partial_downloads: Array<PartialDownload>, active_download: string | null, benchmarks: { [key in string]: BenchmarkResult }, conversations: Array<ConversationSummary>, storage_path: string, 
/**
 * Loaded model and context, if any.
 */
loaded: LoadedModel | null, };
