// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Attachment = { name: string, 
/**
 * Extracted text (for images: text read by OCR); sent to models that can't see images.
 */
text: string, 
/**
 * For images: the saved file (in `images/`), shown to models that can look at images.
 */
image: string | null, };
