// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogModel } from "./CatalogModel";

export type Catalog = { schema: number, 
/**
 * Monotonic; a fetched catalog replaces the current one only if this is higher.
 */
version: bigint, 
/**
 * ISO date, informational.
 */
published: string, models: Array<CatalogModel>, };
