// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatProfile } from "./ChatProfile";
import type { License } from "./License";
import type { MemoryProfile } from "./MemoryProfile";
import type { ModelFile } from "./ModelFile";
import type { Scores } from "./Scores";

export type CatalogModel = { 
/**
 * Stable id; also the model's file name on disk.
 */
id: string, name: string, publisher: string, 
/**
 * One or two plain-language sentences for non-technical people.
 */
summary: string, 
/**
 * Relative quality per use case within this catalog, 1 (basic) to 5 (best). 0 = not suited.
 */
scores: Scores, license: License, file: ModelFile, 
/**
 * The model's image encoder ("projector"), an optional extra download that lets it look
 * at attached images. Absent for text-only models.
 */
vision: ModelFile | null, memory: MemoryProfile, chat: ChatProfile, 
/**
 * Oldest app version that can run this model (e.g. a newer architecture needs a newer llama.cpp).
 */
min_app_version: string, };
