// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Message } from "./Message";
import type { UseCase } from "./UseCase";

export type Conversation = { id: string, title: string, model_id: string, use_case: UseCase, think_harder: boolean, created_at: number, updated_at: number, messages: Array<Message>, };
