// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CpuInfo } from "./CpuInfo";
import type { DeviceIssue } from "./DeviceIssue";
import type { GpuInfo } from "./GpuInfo";
import type { MemoryInfo } from "./MemoryInfo";
import type { Platform } from "./Platform";
import type { StorageInfo } from "./StorageInfo";

export type DeviceInfo = { platform: Platform, os_version: string, 
/**
 * Phone model when the OS tells us ("Pixel 8"), otherwise None.
 */
device_name: string | null, cpu: CpuInfo, memory: MemoryInfo, gpus: Array<GpuInfo>, storage: StorageInfo, issues: Array<DeviceIssue>, };
