// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeviceIssue = { "kind": "cpu_too_old", missing: Array<string>, } | { "kind": "no_gpu_acceleration" };
