// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadError } from "./DownloadError";
import type { LlmError } from "./LlmError";

export type EngineError = { "kind": "unknown_model", id: string, } | { "kind": "not_installed", id: string, } | { "kind": "license_not_accepted", license_id: string, } | { "kind": "download_in_progress", model_id: string, } | { "kind": "download" } & DownloadError | { "kind": "llm" } & LlmError | { "kind": "message_too_long", 
/**
 * Prompt size relative to what fits, e.g. 2.3 = "about 2.3 times too long".
 */
times_too_long: number, } | { "kind": "document", message: string, } | { "kind": "template", message: string, } | { "kind": "no_model_selected" } | { "kind": "unknown_conversation" } | { "kind": "bad_model_file", message: string, } | { "kind": "catalog_unavailable", message: string, } | { "kind": "io", message: string, };
