// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BenchStage } from "./BenchStage";
import type { DownloadError } from "./DownloadError";
import type { Progress } from "./Progress";

export type Event = { "type": "download_progress", model_id: string, progress: Progress, } | { "type": "download_finished", model_id: string, error: DownloadError | null, } | { "type": "import_progress", done: number, total: number, } | { "type": "model_loading", model_id: string, fraction: number, } | { "type": "chat_started", conversation_id: string, message_id: string, 
/**
 * Oldest messages left out so the conversation fits the model.
 */
dropped_messages: number, 
/**
 * Attached documents were longer than the model can read at once, so only the parts
 * most relevant to the question were used.
 */
partial_documents: boolean, } | { "type": "chat_reading", conversation_id: string, fraction: number, } | { "type": "chat_delta", conversation_id: string, message_id: string, thinking: string | null, answer: string | null, } | { "type": "benchmark_stage", model_id: string, stage: BenchStage, };
