// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StopReason } from "./StopReason";

/**
 * Wall-clock measurements of one generation. These are the only speed numbers opnlocal shows.
 */
export type GenerateStats = { prompt_tokens: number, 
/**
 * Prompt tokens actually processed (the rest were reused from the previous turn).
 */
prompt_tokens_processed: number, prompt_ms: number, 
/**
 * From the start of the request to the first generated token.
 */
first_token_ms: number, generated_tokens: number, 
/**
 * Time spent generating after the first token.
 */
generation_ms: number, stop_reason: StopReason, };
