// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GpuKind } from "./GpuKind";

export type GpuInfo = { name: string, 
/**
 * llama.cpp backend ("Vulkan", "Metal").
 */
backend: string, kind: GpuKind, memory_total: number, memory_free: number, 
/**
 * llama.cpp device index (for `LlamaModelParams::with_devices`).
 */
device_index: number, };
