// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryProfile } from "./MemoryProfile";

export type ImportedModel = { id: string, name: string, 
/**
 * File name inside models/.
 */
file: string, size: number, memory: MemoryProfile, imported_at: number, };
