// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type License = { 
/**
 * SPDX id where one exists (e.g. "Apache-2.0"), otherwise a short slug.
 */
id: string, name: string, url: string, 
/**
 * Custom terms the user must read and accept once before downloading.
 */
requires_acceptance: boolean, 
/**
 * Plain-language summary of the conditions, shown before acceptance.
 */
summary: string | null, };
