// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoadInfo } from "./LoadInfo";

export type LoadedModel = { model_id: string, info: LoadInfo, };
