// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemoryInfo = { total: number, available: number, 
/**
 * iOS only: memory this app may still use before the OS stops it.
 */
app_limit: number | null, };
