// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attachment } from "./Attachment";
import type { ReplyStats } from "./ReplyStats";
import type { Role } from "./Role";

export type Message = { id: string, role: Role, content: string, thinking: string | null, attachments: Array<Attachment>, created_at: number, stats: ReplyStats | null, 
/**
 * The reply was stopped by the user before it finished.
 */
stopped: boolean, };
