// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Advanced per-model overrides. None = use the recommended value.
 */
export type ModelSettings = { context: number | null, temperature: number | null, top_p: number | null, max_reply_tokens: number | null, system_prompt: string | null, 
/**
 * Layers on the GPU; None = automatic, 0 = processor only.
 */
gpu_layers: number | null, threads: number | null, 
/**
 * Set by the benchmark on machines whose only GPU is integrated: it measured faster.
 */
use_integrated_gpu: boolean, };
