// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Fit } from "./Fit";
import type { StorageFit } from "./StorageFit";

export type ModelOption = { model_id: string, fit: Fit, storage: StorageFit, 
/**
 * Quality score for the chosen use case (0 = not made for it).
 */
score: number, installed: boolean, };
