// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelOption } from "./ModelOption";
import type { Slot } from "./Slot";

export type Pick = { slot: Slot, option: ModelOption, };
