// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the model runs. Plain words in the UI: graphics chip / both / processor.
 */
export type Placement = "gpu" | "mixed" | "cpu";
