// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelOption } from "./ModelOption";
import type { Pick } from "./Pick";
import type { Unsupported } from "./Unsupported";
import type { UseCase } from "./UseCase";

export type Recommendations = { use_case: UseCase, picks: Array<Pick>, 
/**
 * Every model, best fits first; non-fitting ones carry the reason in `fit`.
 */
all: Array<ModelOption>, unsupported: Unsupported | null, };
