// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Sampling = { temperature: number, top_p: number, top_k: number, min_p: number, };
