// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GpuCrash } from "./GpuCrash";
import type { ModelSettings } from "./ModelSettings";
import type { UseCase } from "./UseCase";

export type Settings = { onboarding_done: boolean, use_case: UseCase | null, 
/**
 * Model used for new chats.
 */
active_model: string | null, 
/**
 * Refresh the model list at most once a day. Off = never goes online on its own.
 */
auto_refresh_catalog: boolean, 
/**
 * Unix seconds of the last catalog check.
 */
last_catalog_check: number | null, 
/**
 * License id → unix seconds when accepted.
 */
accepted_licenses: Record<string, number>, 
/**
 * User turned graphics acceleration off in Advanced.
 */
gpu_disabled: boolean, 
/**
 * Set when the app died while loading a model on the GPU; GPU stays off until re-enabled.
 */
gpu_crash: GpuCrash | null, per_model: { [key in string]: ModelSettings }, };
