// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StorageFit = { ok: boolean, 
/**
 * Space needed on disk for the download (plus margin).
 */
need_bytes: number, 
/**
 * How much must be freed (0 if ok).
 */
short_by_bytes: number, };
