// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThinkingControl = { "kind": "unsupported" } | { "kind": "template_flag", variable: string, } | { "kind": "always_on", variable: string, normal: string, harder: string, } | { "kind": "always" };
