// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Unsupported = { "kind": "cpu_too_old" } | { "kind": "not_enough_memory", smallest_need_bytes: number, };
